# Generated by Django 6.0.4 on 2026-04-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('image_src', models.CharField(max_length=200)),
                ('img_width', models.IntegerField(default=0)),
                ('img_height', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_url', models.CharField(max_length=200)),
                ('img_width', models.IntegerField(default=0)),
                ('img_height', models.IntegerField(default=0)),
                ('celebrity_url', models.CharField(max_length=200)),
                ('celebrity_name', models.CharField(max_length=50)),
                ('celebrity_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_src', models.CharField(max_length=200)),
                ('img_width', models.IntegerField(default=0)),
                ('img_height', models.IntegerField(default=0)),
                ('anchor_url', models.CharField(max_length=200)),
                ('movie_genre', models.CharField(max_length=10)),
                ('movie_title', models.CharField(max_length=20)),
                ('lower_rating', models.CharField(max_length=5)),
                ('upper_rating', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('anchor_class', models.CharField(max_length=2)),
                ('icon_class', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_URL', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TrailerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.CharField(max_length=200)),
                ('img_alt', models.CharField(max_length=100)),
                ('img_width', models.IntegerField(default=0)),
                ('img_height', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=10)),
            ],
        ),
    ]
