# Generated by Django 6.0.4 on 2026-04-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_advertisement_celebrity_slider_sociallink_trailer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='img_src',
            field=models.CharField(default='app1/images/uploads/ava1.jpg', max_length=200),
        ),
    ]
